### ISSUE TITLE
This script is broken for the newer versions of nfsiostat on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by diogouchoas** [ovido/check_nfs_io#1]
This check script works fine on most Linux distributions, however on Ubuntu 14.04 it isn't working. The script isn't capable of checking the values of the nfsiostat output, so no performance data shows up on the check output.

```
NFS I/O OK:  [Mount points: /var/www]|
```

It's nfsiostat command fault, because the values aren't being aligned with the columns they represent:

```
192.168.17.1:/var/www mounted on /var/www:

   op/s     rpc bklog
   0.60
       0.00
read:          
  ops/s        kB/s       kB/op     retrans     avg RTT (ms)    avg exe (ms)
          0.013
      2.150
    169.751
       0 (0.0%)
     11.842
     11.960
write:         
  ops/s        kB/s       kB/op     retrans     avg RTT (ms)    avg exe (ms)
          0.000
      0.061
    453.392
       0 (0.0%)
     97.151
    120.760
```

Is there an easy patch I can do to adapt to this nfsiostat problem?

**Comment by scrat14** [comment]
This script was intitially written for RHEL 5/6 and Solaris 10/11. I'll test it with Ubuntu and provide a patch...
Thanks for reporting this issue.

**Comment by diogouchoas** [comment]
Hi scrat14,

actually I found out it was an error on the nfsiostat binary itself. The nfs-utils package in many of the debian based distributions is bugged and showing the values out of order. I was able to solve the problem using [this version](https://github.com/KunX/nfs-utils/blob/master/tools/nfs-iostat/nfs-iostat.py) of nfsiostat in place of the native one.
