### ISSUE TITLE
whitespace in performance data

### ISSUE THREAD

**Issue by bardahlm** [ovido/check_nfs_io#2]
Lines 331 and 334 in check_nfs_io/plugin-dir/check_nfs_io.pl have an extra whitespace between the value and the UOM in the performance data.
`      $perfstats .= "'" . $nfsshare . "_r_avg_rtt'=$value " . "ms;;;0; ";`

should be changed to
`      $perfstats .= "'" . $nfsshare . "_r_avg_rtt'=$value" . "ms;;;0; ";`

**Comment by scrat14** [comment]
Thanks for reporting this issue - I'll fix it in the next days.
